# Generated by Django 3.2.3 on 2021-06-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_city_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='county',
            new_name='country',
        ),
    ]
